global class Calculator{
	// Adding some comment to test Github push

   Static webservice Integer add(Integer x,Integer y)
      {
           return x+y;
           
           }           

   Static webservice Integer sub(Integer x, Integer y)
      {
           return x-y;
           
           }           
       public Integer multiple(Integer x,Integer y)
      {
           return x*y;
           
           }
           
           
   }